### PR TITLE
tracking options foreground service

### PR DESCRIPTION
**Pull request by brettguenther**
## What?

Outline foreground service tracking option use.

## Why?

Currently not documented at this level of detail.

### CODE REVIEW

**Comment by brettguenther** [comment]
@jsani-radar - for friday reviews :) - debated on the data types inclusion. If valuable probably makes sense to mimic it for other tracking options + make sure we have all defaults documented.

**Comment by nickpatrick** [comment]
Thanks @brettguenther. I was actually planning to get to this as part of SDK 3.2 docs. This looks solid, just a couple bits of feedback on first glance:
- I might change the headline to `Android foreground service options`. Alternatively or in addition, we might want to mention the class name `RadarTrackingOptionsForegroundService` somewhere.
- The default for notification importance is currently `android.app.NotificationManager.IMPORTANCE_DEFAULT` instead of high: https://github.com/radarlabs/radar-sdk-android/blob/master/sdk/src/main/java/io/radar/sdk/RadarTrackingOptions.kt#L274 https://github.com/radarlabs/radar-sdk-android/blob/master/sdk/src/main/java/io/radar/sdk/RadarForegroundService.kt#L51
- Looks like we're deviating from the SDK docs a bit: https://github.com/radarlabs/radar-sdk-android/blob/master/sdk/src/main/java/io/radar/sdk/RadarTrackingOptions.kt#L247 We should prob try to keep things consistent. If we think some of these edits make the options more understandable, I can incorporate them into the SDK 3.2 PR.
- I like the idea of including data types like `string`. Do we also want to include optional/required? General point that we should probably to keep type names and formatting consistent across the docs. I also wonder if moving all of the tracking options into a table (instead of bullet points) is more readable. Same applies to API params.

**Comment by jsani-radar** [comment]
how to populate `foreground` has been a consistent question from customers using React Native - think we should put links to this section in the Android / RN SDK docs. We might even want a new section like "Background tracking for workforce / always on"

**Comment by jsani-radar** [comment]
where did we end up on this PR @brettguenther? do we want to merge the foreground service options as is or think about larger structural changes?

**Comment by jsani-radar** [comment]
Seems to be already present on the page - https://radar.io/documentation/sdk/tracking#android-foreground-service-options

**Pull request closed without merging**
