### PR TITLE
Add location verification FAQ

### PR DESCRIPTION
**Pull request by nickpatrick**
## What?
- Add information about our location verification and fraud detection capabilities

## Why?
- For reference by our customers, partners, and legal teams

### CODE REVIEW

**Review by andlum — APPROVED** [review]
Looks good!

**Review by andlum — CHANGES_REQUESTED** [review]
Oops! Sorry, I spoke too soon: I think the links need to remove the `/documentation` part - this is because Docusaurus swaps updates all links in markdown based on the `baseUrl` that we set in our docusaurus config e.g.

```md
[IP geocoding API](/documentation/api#ip-geocode)
``` 

should be:
```md
[IP geocoding API](/api#ip-geocode)
```

**Comment by nickpatrick** [comment]
@andlum Ah, got it. Fixing

**Comment by nickpatrick** [comment]
✅

**Review by andlum — APPROVED** [review]
Looks good

**Pull request merged**
