### PR TITLE
Adding examples to the Waypoint page in docs

### PR DESCRIPTION
**Pull request by vivekjain1397**
Adding the following examples to the Waypoint docs: 

- Testing on-premise mode
- Testing trips 
- Testing background mode
- Testing beacons

### CODE REVIEW

**Comment by KennyHuRadar** [comment]
Seems correct to me, @lmeier can you take a look so that we can merge this?

**Comment by vivekjain1397** [comment]
@lmeier are you able to quickly review/merge this in today?

**Review by lmeier — COMMENTED** [review]
@vivekjain1397 this looks good generally. Did you experiment with showing the Waypoint screenshots in any different ways. They have a lot of vertical height and little width -- I wonder if we can have them in line with the text / otherwise make this guide appear a bit nicer.

**Comment by vivekjain1397** [comment]
> > @vivekjain1397 this looks good generally. Did you experiment with showing the Waypoint screenshots in any different ways. They have a lot of vertical height and little width -- I wonder if we can have them in line with the text / otherwise make this guide appear a bit nicer.
> 
> @lmeier fixed formatting so all images are below the steps and have references, looks much nicer than having them inline. Lmk what you think

@lmeier wanted to bump this - are you good with this formatting?

**Pull request merged**
