### PR TITLE
Tracking options updates

### PR DESCRIPTION
**Pull request by nickpatrick**
- Documents `syncGeofencesLimit`, `useForegroundService`, and `beacons`
- Updates preset descriptions to match SDK docs

To be merged after we release https://github.com/radarlabs/radar-sdk-android/pull/121 for Android

See also https://github.com/radarlabs/radar-sdk-ios/pull/118/files for iOS updates

### CODE REVIEW

**Comment by jkao** [comment]
For iOS:

`desiredSyncInterval` for responsive is `20`

**Comment by jkao** [comment]
For iOS:

`sync` is `.all` for responsive

**Comment by jkao** [comment]
For iOS:

`sync` is `.all` for efficient

**Comment by jkao** [comment]
For iOS:

`syncGeofences` is `true` for efficient

**Comment by jkao** [comment]
iOS `continuous` looks good

**Comment by jkao** [comment]
For Android:

`syncGeofencesLimit` is 0 for continuous

**Comment by jkao** [comment]
For Android:

`desiredSyncInterval` is 20 for responsive

**Comment by jkao** [comment]
For Android:

`sync` is `ALL` for responsive

**Comment by jkao** [comment]
For Android:

`sync` is `ALL` for efficient

**Comment by jkao** [comment]
For Android efficient:

`syncGeofences` is true and `syncGeofencesLimit` is 10

**Comment by nickpatrick** [comment]
@jkao Thanks for these edits. Want to approve and I'll merge again?

**Review by jkao — APPROVED** [review]

**Pull request merged**
