### PR TITLE
chore: [sc-11185] add fullstory to docs

### PR DESCRIPTION
**Pull request by corypisano**
Story details: https://app.shortcut.com/radarlabs/story/11185

More details on ticket

### CODE REVIEW

**Comment by corypisano** [comment]
k can see it gets unmasked halfway through here 
https://app.fullstory.com/ui/8TP1K/session/6012859036930048:(6012859036930048!5836067060518912(5010063723270144(1:1:936):6729735174819840(0)))

**Comment by jsani-radar** [comment]
lgtm overall! thank you so, so much for this

do you have an example session in FS where it's functioning properly with the elements unmasked?

**Comment by corypisano** [comment]
yea I added to the [ticket](https://app.shortcut.com/radarlabs/story/11185/add-fullstory-to-docs) comments

**Comment by bschoeneweis** [comment]
Does anything here actually need to be masked?  Nothing really sensitive at all (or maybe I'm misunderstanding the use case of masking)

**Comment by corypisano** [comment]
> Does anything here actually need to be masked? Nothing really sensitive at all (or maybe I'm misunderstanding the use case of masking)

Nope, added the unmasking at the top level. Just uses the same masking default as dashboard

**Review by jsani-radar — APPROVED** [review]

**Pull request merged**
