### PR TITLE
Olo integration docs refresh

### PR DESCRIPTION
**Pull request by brettguenther**
## What?

Update our Olo integration docs

## Why?

Instructions are dated

### CODE REVIEW

**Comment by jsani-radar** [comment]
do we need the package updates? seems like they're tangential to this PR's purpose

**Comment by brettguenther** [comment]
> do we need the package updates? seems like they're tangential to this PR's purpose

we do not. reverted package.json

**Comment by jsani-radar** [comment]
content looks solid, but still seeing changes to `package-lock.json`, probably propagated from the earlier `package.json` changes - seems like we'll need a `git rm --cached` or `git reset` on that file https://stackoverflow.com/a/38001958

**Comment by brettguenther** [comment]
> content looks solid, but still seeing changes to `package-lock.json`, probably propagated from the earlier `package.json` changes - seems like we'll need a `git rm --cached` or `git reset` on that file https://stackoverflow.com/a/38001958

thanks @jsani-radar - think i have it reverted now so should hopefully be good for friday docs review.

**Review by jsani-radar — APPROVED** [review]

**Pull request merged**
