### PR TITLE
Update api.mdx

### PR DESCRIPTION
**Pull request by ahwreck**
Update PATCH Trips to Secret authentication

### CODE REVIEW

**Comment by ahwreck** [comment]
actually looks like its publishable in the API code. shouldn't this be secret?

https://github.com/radarlabs/server/blob/4107ce191fa731f90fc88f9927e5595bc110aca0/server/routes/apiV1Router.ts#L182

**Comment by kochis** [comment]
I don't think so, since this is intended to be called from the client

**Comment by ahwreck** [comment]
ok - in Hathway's case w/ SnS they are calling it from middleware (NomNom) to set the scheduledArrivalAt timestamp as well. guess to allow it to be called from the client keeping it publishable makes sense.

**Comment by ahwreck** [comment]
do we want to include all the other object fields you can potentially PATCH on a trip as well in the docs?

**Comment by jsani-radar** [comment]
what's the status of this PR @ahwreck? did you want to add the PATCH params or should it be closed?

**Comment by ahwreck** [comment]
No changes needed

**Pull request closed without merging**
